import os
from pathlib import Path
from jackdaw.server.services.coral import run_query
from jackdaw.config import ConfigManager

BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
QUERIES_DIR = BASE_DIR / "queries"

class QueryEngine:
    @staticmethod
    def _get_active_github_target() -> tuple[str, str]:
        """
        Dynamically extracts the owner and repo based on the active workspace.
        """
        context = ConfigManager.get_full_context()
        user_config = context.get("user", {})
        
        # Check which workspace the user wants to use right now
        jackdaw_settings = user_config.get("jackdaw", {})
        active_ws_name = jackdaw_settings.get("active_workspace", "default")
        
        # Look up the repository details for that specific workspace
        workspaces = user_config.get("workspaces", {})
        active_ws = workspaces.get(active_ws_name, {})
        
        # Fallback to defaults if the config is misconfigured
        owner = active_ws.get("owner", "withcoral")
        repo = active_ws.get("repo", "coral")
        
        return owner, repo

    @staticmethod
    def _load_sql_file(filename: str, **kwargs) -> str:
        """Reads a .sql file, strips comments, and injects dynamic variables."""
        filepath = QUERIES_DIR / filename
        if not filepath.exists():
            raise FileNotFoundError(f"Query file not found: {filepath}")
        
        with open(filepath, "r") as file:
            lines = file.readlines()
            clean_lines = [line.strip() for line in lines if not line.strip().startswith("--")]
            clean_sql = " ".join(clean_lines)
            return clean_sql.format(**kwargs)

    @staticmethod
    def get_daily_snapshot():
        """Executes the daily snapshot query using active workspace targets."""
        owner, repo = QueryEngine._get_active_github_target()
        sql = QueryEngine._load_sql_file(
            "daily_snapshot.sql", 
            github_owner=owner, 
            github_repo=repo
        )
        return run_query(sql)

    @staticmethod
    def get_code_to_cash_metrics():
        """Executes the cross-source join using active workspace targets."""
        owner, repo = QueryEngine._get_active_github_target()
        sql = QueryEngine._load_sql_file(
            "code_to_cash.sql", 
            github_owner=owner, 
            github_repo=repo
        )
        return run_query(sql)

    @staticmethod
    def get_active_schema() -> list:
        """Fetches all available tables across connected sources."""
        sql = "SELECT schema_name, table_name FROM coral.tables WHERE schema_name != 'coral'"
        return run_query(sql)

    @staticmethod
    def execute_raw_sql(sql: str) -> list:
        """Executes a dynamic SQL string generated by Anne."""
        return run_query(sql)